In [4]:
import pandas as pd

df = pd.read_csv(r'C:\Users\MINA\Documents\WeekilyPrac\Ml_JOUNRAL\ml-learning-journal\Time Series\Datasets\shampoo_sales.csv')

df.head()

  Month  Sales
0  1-01  266.0
1  1-02  145.9
2  1-03  183.1
3  1-04  119.3
4  1-05  180.3

In [5]:
import pandas as pd

df["Month"] = "190" + df["Month"]

df["Month"] = pd.to_datetime(
    df["Month"],
    format="%Y-%m"
)

df.set_index("Month", inplace=True)

print(df.head())

            Sales
Month
1901-01-01  266.0
1901-02-01  145.9
1901-03-01  183.1
1901-04-01  119.3
1901-05-01  180.3

In [6]:
sales_data = {
    "date": [
        "2021-01-01", "2021-02-01", "2021-03-01", "2021-04-01",
        "2021-05-01", "2021-06-01", "2021-07-01", "2021-08-01",
        "2021-09-01", "2021-10-01", "2021-11-01", "2021-12-01",

        "2022-01-01", "2022-02-01", "2022-03-01", "2022-04-01",
        "2022-05-01", "2022-06-01", "2022-07-01", "2022-08-01",
        "2022-09-01", "2022-10-01", "2022-11-01", "2022-12-01",

        "2023-01-01", "2023-02-01", "2023-03-01", "2023-04-01",
        "2023-05-01", "2023-06-01", "2023-07-01", "2023-08-01",
        "2023-09-01", "2023-10-01", "2023-11-01", "2023-12-01",

        "2024-01-01", "2024-02-01", "2024-03-01", "2024-04-01",
        "2024-05-01", "2024-06-01", "2024-07-01", "2024-08-01",
        "2024-09-01", "2024-10-01", "2024-11-01", "2024-12-01",

        "2025-01-01", "2025-02-01", "2025-03-01", "2025-04-01",
        "2025-05-01", "2025-06-01", "2025-07-01", "2025-08-01",
        "2025-09-01", "2025-10-01", "2025-11-01", "2025-12-01"
    ],

    "sales": [
        120, 128, 135, 142, 150, 158, 165, 170, 180, 205, 225, 260,
        135, 142, 150, 158, 166, 174, 182, 190, 202, 225, 248, 285,
        150, 158, 167, 175, 184, 193, 202, 212, 225, 250, 275, 315,
        168, 176, 185, 195, 205, 215, 226, 237, 250, 278, 305, 350,
        185, 194, 204, 215, 226, 237, 249, 262, 276, 305, 335, 385
    ]
}

In [9]:
df = pd.DataFrame(sales_data)
df.head()

         date  sales
0  2021-01-01    120
1  2021-02-01    128
2  2021-03-01    135
3  2021-04-01    142
4  2021-05-01    150

In [11]:
df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)

In [13]:
df['Month_Name'] = df.index.month_name()

month_avg = df.groupby('Month_Name')['sales'].mean()

month_avg

Month_Name
April        177.0
August       214.2
December     319.0
February     159.6
January      151.6
July         204.8
June         195.4
March        168.2
May          186.2
November     277.6
October      252.6
September    226.6
Name: sales, dtype: float64